/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SDC PERFORMANCE™️ (https://sketchfab.com/Lambo_SC04)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dji-fpv-by-sdc-high-performance-drone-d471ea8c6235457b8e131842e2cf3783
Title: Dji FPV by SDC -  High performance drone
*/

import * as THREE from 'three'
import React, { useRef, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { ThreeElements } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Object_5: THREE.Mesh
    Object_6: THREE.Mesh
    Object_7: THREE.Mesh
    Object_8: THREE.Mesh
    Object_9: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_17: THREE.Mesh
    Object_18: THREE.Mesh
    Object_19: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_23: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_27: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_31: THREE.Mesh
    Object_32: THREE.Mesh
    Object_33: THREE.Mesh
    Object_34: THREE.Mesh
    Object_35: THREE.Mesh
    Object_36: THREE.Mesh
    Object_37: THREE.Mesh
    Object_38: THREE.Mesh
    Object_40: THREE.Mesh
    Object_41: THREE.Mesh
    Object_42: THREE.Mesh
    Object_44: THREE.Mesh
    Object_45: THREE.Mesh
    Object_46: THREE.Mesh
    Object_47: THREE.Mesh
    Object_49: THREE.Mesh
    Object_50: THREE.Mesh
    Object_52: THREE.Mesh
    Object_54: THREE.Mesh
    Object_56: THREE.Mesh
    Object_57: THREE.Mesh
    Object_58: THREE.Mesh
    Object_60: THREE.Mesh
    Object_61: THREE.Mesh
    Object_62: THREE.Mesh
    Object_64: THREE.Mesh
    Object_65: THREE.Mesh
    Object_66: THREE.Mesh
    Object_68: THREE.Mesh
    Object_70: THREE.Mesh
    Object_71: THREE.Mesh
    Object_72: THREE.Mesh
    Object_74: THREE.Mesh
    Object_75: THREE.Mesh
    Object_77: THREE.Mesh
    Object_78: THREE.Mesh
    Object_80: THREE.Mesh
    Object_81: THREE.Mesh
    Object_83: THREE.Mesh
    Object_84: THREE.Mesh
    Object_85: THREE.Mesh
    Object_87: THREE.Mesh
    Object_88: THREE.Mesh
    Object_90: THREE.Mesh
    Object_91: THREE.Mesh
    Object_92: THREE.Mesh
    Object_94: THREE.Mesh
    Object_95: THREE.Mesh
    Object_96: THREE.Mesh
    Object_97: THREE.Mesh
    Object_98: THREE.Mesh
    Object_99: THREE.Mesh
    Object_101: THREE.Mesh
    Object_102: THREE.Mesh
    Object_103: THREE.Mesh
    Object_104: THREE.Mesh
    Object_106: THREE.Mesh
    Object_108: THREE.Mesh
    Object_109: THREE.Mesh
    Object_110: THREE.Mesh
    Object_111: THREE.Mesh
    Object_113: THREE.Mesh
    Object_114: THREE.Mesh
    Object_115: THREE.Mesh
    Object_117: THREE.Mesh
    Object_119: THREE.Mesh
    Object_120: THREE.Mesh
    Object_121: THREE.Mesh
    Object_122: THREE.Mesh
    Object_124: THREE.Mesh
    Object_126: THREE.Mesh
    Object_127: THREE.Mesh
    Object_128: THREE.Mesh
    Object_129: THREE.Mesh
    Object_130: THREE.Mesh
    Object_131: THREE.Mesh
    Object_132: THREE.Mesh
    Object_133: THREE.Mesh
    Object_135: THREE.Mesh
    Object_136: THREE.Mesh
    Object_138: THREE.Mesh
    Object_140: THREE.Mesh
    Object_142: THREE.Mesh
    Object_143: THREE.Mesh
    Object_144: THREE.Mesh
    Object_146: THREE.Mesh
    Object_147: THREE.Mesh
    Object_148: THREE.Mesh
    Object_150: THREE.Mesh
    Object_151: THREE.Mesh
    Object_153: THREE.Mesh
    Object_155: THREE.Mesh
    Object_156: THREE.Mesh
    Object_158: THREE.Mesh
    Object_160: THREE.Mesh
    Object_162: THREE.Mesh
    Object_163: THREE.Mesh
    Object_164: THREE.Mesh
    Object_165: THREE.Mesh
    Object_166: THREE.Mesh
    Object_167: THREE.Mesh
    Object_169: THREE.Mesh
    // Object_171: THREE.Mesh
    // Object_173: THREE.Mesh
  }
  materials: {
    M_D1: THREE.MeshStandardMaterial
    Plastic_D1: THREE.MeshStandardMaterial
    Plastic_L1: THREE.MeshStandardMaterial
    Plastic_D2: THREE.MeshStandardMaterial
    Metall_Basic: THREE.MeshStandardMaterial
    ['Material.009']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['Material.007']: THREE.MeshStandardMaterial
    Grey_L1: THREE.MeshStandardMaterial
    Grey_Basic: THREE.MeshStandardMaterial
    ['Material.005']: THREE.MeshStandardMaterial
    Grey_D2: THREE.MeshStandardMaterial
    Rubber_L1: THREE.MeshStandardMaterial
    Rubber_Basic: THREE.MeshStandardMaterial
    Rubber_D1: THREE.MeshStandardMaterial
    Plastic_L2: THREE.MeshStandardMaterial
    Plastic_Base: THREE.MeshStandardMaterial
    ['Material.004']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    M_L1: THREE.MeshStandardMaterial
    Grey_D1: THREE.MeshStandardMaterial
    CARBONE: THREE.MeshStandardMaterial
    ['Material.006']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    Metall_D2: THREE.MeshStandardMaterial
    Mettal_L1: THREE.MeshStandardMaterial
    Metall_D1: THREE.MeshStandardMaterial
    Green_L1: THREE.MeshStandardMaterial
    Green_L2E: THREE.MeshStandardMaterial
    M_Basic: THREE.MeshStandardMaterial
    M_D2: THREE.MeshStandardMaterial
    Red_L1: THREE.MeshStandardMaterial
    Red_Basic: THREE.MeshStandardMaterial
    Red_D1: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    ['Material.008']: THREE.MeshStandardMaterial
    Yellow_L1: THREE.MeshStandardMaterial
    ['Material.011']: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Rubber_Tire.002']: THREE.MeshStandardMaterial
    ['Material.010']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
  }
}

export function Model(props: ThreeElements['group']) {
  const { nodes, materials } = useGLTF('/models/dji_drone.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group
        name="Empty_46"
        position={[0, 1.01656961, -0.13504228]}
        rotation={[-0.47512635, 0, 0]}
        scale={3.53094292}>
        <group name="camera2002_0" rotation={[-Math.PI / 2, 0, 0]} scale={0.28321052}>
          <mesh
            name="Object_5"
            castShadow
            receiveShadow
            geometry={nodes.Object_5.geometry}
            material={materials.M_D1}
          />
          <mesh
            name="Object_6"
            castShadow
            receiveShadow
            geometry={nodes.Object_6.geometry}
            material={materials.Plastic_D1}
          />
          <mesh
            name="Object_7"
            castShadow
            receiveShadow
            geometry={nodes.Object_7.geometry}
            material={materials.Plastic_L1}
          />
          <mesh
            name="Object_8"
            castShadow
            receiveShadow
            geometry={nodes.Object_8.geometry}
            material={materials.Plastic_D2}
          />
          <mesh
            name="Object_9"
            castShadow
            receiveShadow
            geometry={nodes.Object_9.geometry}
            material={materials.Metall_Basic}
          />
          <mesh
            name="Object_10"
            castShadow
            receiveShadow
            geometry={nodes.Object_10.geometry}
            material={materials['Material.009']}
          />
        </group>
        <group name="Cube178_3" rotation={[0.41589933, 0.01534926, 0.07591526]} scale={0.28321049}>
          <mesh
            name="Object_16"
            castShadow
            receiveShadow
            geometry={nodes.Object_16.geometry}
            material={materials.Grey_L1}
          />
          <mesh
            name="Object_17"
            castShadow
            receiveShadow
            geometry={nodes.Object_17.geometry}
            material={materials.Grey_Basic}
          />
          <mesh
            name="Object_18"
            castShadow
            receiveShadow
            geometry={nodes.Object_18.geometry}
            material={materials['Material.005']}
          />
          <mesh
            name="Object_19"
            castShadow
            receiveShadow
            geometry={nodes.Object_19.geometry}
            material={materials.Grey_D2}
          />
          <mesh
            name="Object_20"
            castShadow
            receiveShadow
            geometry={nodes.Object_20.geometry}
            material={materials.Plastic_D1}
          />
        </group>
        <group name="Cube179_4" rotation={[0.50162032, 0, 0]} scale={0.28321052}>
          <mesh
            name="Object_22"
            castShadow
            receiveShadow
            geometry={nodes.Object_22.geometry}
            material={materials.Rubber_L1}
          />
          <mesh
            name="Object_23"
            castShadow
            receiveShadow
            geometry={nodes.Object_23.geometry}
            material={materials.Rubber_Basic}
          />
          <mesh
            name="Object_24"
            castShadow
            receiveShadow
            geometry={nodes.Object_24.geometry}
            material={materials.Rubber_D1}
          />
        </group>
        <group name="Cube180_5" rotation={[0.44645264, 0, 0]} scale={0.28321052}>
          <mesh
            name="Object_26"
            castShadow
            receiveShadow
            geometry={nodes.Object_26.geometry}
            material={materials.Plastic_D1}
          />
          <mesh
            name="Object_27"
            castShadow
            receiveShadow
            geometry={nodes.Object_27.geometry}
            material={materials.Rubber_Basic}
          />
          <mesh
            name="Object_28"
            castShadow
            receiveShadow
            geometry={nodes.Object_28.geometry}
            material={materials.Plastic_D2}
          />
        </group>
        <group name="Cube181_6" rotation={[0.62204902, 0, 0]} scale={0.28321052}>
          <mesh
            name="Object_30"
            castShadow
            receiveShadow
            geometry={nodes.Object_30.geometry}
            material={materials.Grey_D2}
          />
          <mesh
            name="Object_31"
            castShadow
            receiveShadow
            geometry={nodes.Object_31.geometry}
            material={materials.Plastic_D1}
          />
          <mesh
            name="Object_32"
            castShadow
            receiveShadow
            geometry={nodes.Object_32.geometry}
            material={materials.Rubber_Basic}
          />
          <mesh
            name="Object_33"
            castShadow
            receiveShadow
            geometry={nodes.Object_33.geometry}
            material={materials.Plastic_L2}
          />
          <mesh
            name="Object_34"
            castShadow
            receiveShadow
            geometry={nodes.Object_34.geometry}
            material={materials.Plastic_L1}
          />
          <mesh
            name="Object_35"
            castShadow
            receiveShadow
            geometry={nodes.Object_35.geometry}
            material={materials.Plastic_Base}
          />
          <mesh
            name="Object_36"
            castShadow
            receiveShadow
            geometry={nodes.Object_36.geometry}
            material={materials.Plastic_D2}
          />
          <mesh
            name="Object_37"
            castShadow
            receiveShadow
            geometry={nodes.Object_37.geometry}
            material={materials['Material.004']}
          />
          <mesh
            name="Object_38"
            castShadow
            receiveShadow
            geometry={nodes.Object_38.geometry}
            material={materials['Material.013']}
          />
        </group>
        <group
          name="Cube182_7"
          rotation={[-0.00036557, 0, 0]}
          scale={[0.28321052, 0.28321046, 0.28321046]}>
          <mesh
            name="Object_40"
            castShadow
            receiveShadow
            geometry={nodes.Object_40.geometry}
            material={materials.M_L1}
          />
          <mesh
            name="Object_41"
            castShadow
            receiveShadow
            geometry={nodes.Object_41.geometry}
            material={materials.Grey_D1}
          />
          <mesh
            name="Object_42"
            castShadow
            receiveShadow
            geometry={nodes.Object_42.geometry}
            material={materials.Plastic_Base}
          />
        </group>
        <group name="Cube183_8" scale={0.28321052}>
          <mesh
            name="Object_44"
            castShadow
            receiveShadow
            geometry={nodes.Object_44.geometry}
            material={materials.Grey_L1}
          />
          <mesh
            name="Object_45"
            castShadow
            receiveShadow
            geometry={nodes.Object_45.geometry}
            material={materials.Grey_Basic}
          />
          <mesh
            name="Object_46"
            castShadow
            receiveShadow
            geometry={nodes.Object_46.geometry}
            material={materials['Material.005']}
          />
          <mesh
            name="Object_47"
            castShadow
            receiveShadow
            geometry={nodes.Object_47.geometry}
            material={materials.Grey_D2}
          />
        </group>
        <group name="Cube184_9" scale={0.28321052}>
          <mesh
            name="Object_49"
            castShadow
            receiveShadow
            geometry={nodes.Object_49.geometry}
            material={materials.Grey_D1}
          />
          <mesh
            name="Object_50"
            castShadow
            receiveShadow
            geometry={nodes.Object_50.geometry}
            material={materials.CARBONE}
          />
        </group>
        <group name="Cube187_12" scale={0.28321052}>
          <mesh
            name="Object_56"
            castShadow
            receiveShadow
            geometry={nodes.Object_56.geometry}
            material={materials.Plastic_D1}
          />
          <mesh
            name="Object_57"
            castShadow
            receiveShadow
            geometry={nodes.Object_57.geometry}
            material={materials.Plastic_L1}
          />
          <mesh
            name="Object_58"
            castShadow
            receiveShadow
            geometry={nodes.Object_58.geometry}
            material={materials.Plastic_Base}
          />
        </group>
        <group name="Cube188_13" scale={0.28321052}>
          <mesh
            name="Object_60"
            castShadow
            receiveShadow
            geometry={nodes.Object_60.geometry}
            material={materials.Plastic_D1}
          />
          <mesh
            name="Object_61"
            castShadow
            receiveShadow
            geometry={nodes.Object_61.geometry}
            material={materials.Rubber_L1}
          />
          <mesh
            name="Object_62"
            castShadow
            receiveShadow
            geometry={nodes.Object_62.geometry}
            material={materials.Plastic_L1}
          />
        </group>
        <group name="Cube189_14" scale={0.28321052}>
          <mesh
            name="Object_64"
            castShadow
            receiveShadow
            geometry={nodes.Object_64.geometry}
            material={materials.M_D1}
          />
          <mesh
            name="Object_65"
            castShadow
            receiveShadow
            geometry={nodes.Object_65.geometry}
            material={materials.Plastic_D1}
          />
          <mesh
            name="Object_66"
            castShadow
            receiveShadow
            geometry={nodes.Object_66.geometry}
            material={materials.Plastic_Base}
          />
        </group>
        <group name="Cube195_16" scale={0.28321052}>
          <mesh
            name="Object_70"
            castShadow
            receiveShadow
            geometry={nodes.Object_70.geometry}
            material={materials.Mettal_L1}
          />
          <mesh
            name="Object_71"
            castShadow
            receiveShadow
            geometry={nodes.Object_71.geometry}
            material={materials.Metall_Basic}
          />
          <mesh
            name="Object_72"
            castShadow
            receiveShadow
            geometry={nodes.Object_72.geometry}
            material={materials.Metall_D1}
          />
        </group>
        <group name="Cube196_17" scale={0.28321052}>
          <mesh
            name="Object_74"
            castShadow
            receiveShadow
            geometry={nodes.Object_74.geometry}
            material={materials.Plastic_D1}
          />
          <mesh
            name="Object_75"
            castShadow
            receiveShadow
            geometry={nodes.Object_75.geometry}
            material={materials.Plastic_L1}
          />
        </group>
        <group
          name="Cube197_18"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[0.31590846, 0.28321052, 0.28321052]}>
          <mesh
            name="Object_77"
            castShadow
            receiveShadow
            geometry={nodes.Object_77.geometry}
            material={materials.Plastic_Base}
          />
          <mesh
            name="Object_78"
            castShadow
            receiveShadow
            geometry={nodes.Object_78.geometry}
            material={materials.Metall_D2}
          />
        </group>
        <group name="Cube198_19" scale={0.28321052}>
          <mesh
            name="Object_80"
            castShadow
            receiveShadow
            geometry={nodes.Object_80.geometry}
            material={materials.Grey_D1}
          />
          <mesh
            name="Object_81"
            castShadow
            receiveShadow
            geometry={nodes.Object_81.geometry}
            material={materials.Grey_D2}
          />
        </group>
        <group
          name="Cube199_20"
          rotation={[-0.00036557, 0, 0]}
          scale={[0.28321052, 0.28321046, 0.28321046]}>
          <mesh
            name="Object_83"
            castShadow
            receiveShadow
            geometry={nodes.Object_83.geometry}
            material={materials.Grey_Basic}
          />
          <mesh
            name="Object_84"
            castShadow
            receiveShadow
            geometry={nodes.Object_84.geometry}
            material={materials.Grey_D1}
          />
          <mesh
            name="Object_85"
            castShadow
            receiveShadow
            geometry={nodes.Object_85.geometry}
            material={materials.Grey_D2}
          />
        </group>
        <group name="Cube200_21" scale={0.28321052}>
          <mesh
            name="Object_87"
            castShadow
            receiveShadow
            geometry={nodes.Object_87.geometry}
            material={materials.Green_L1}
          />
          <mesh
            name="Object_88"
            castShadow
            receiveShadow
            geometry={nodes.Object_88.geometry}
            material={materials.Green_L2E}
          />
        </group>
        <group
          name="Cube201_22"
          rotation={[1.11716212, 0, 0]}
          scale={[0.28321052, 0.28321049, 0.28321049]}>
          <mesh
            name="Object_90"
            castShadow
            receiveShadow
            geometry={nodes.Object_90.geometry}
            material={materials.Rubber_Basic}
          />
          <mesh
            name="Object_91"
            castShadow
            receiveShadow
            geometry={nodes.Object_91.geometry}
            material={materials.Rubber_D1}
          />
          <mesh
            name="Object_92"
            castShadow
            receiveShadow
            geometry={nodes.Object_92.geometry}
            material={materials.Plastic_L2}
          />
        </group>
        <group name="Cube202_23" rotation={[0.64417989, 0, 0]} scale={0.28321052}>
          <mesh
            name="Object_94"
            castShadow
            receiveShadow
            geometry={nodes.Object_94.geometry}
            material={materials.M_Basic}
          />
          <mesh
            name="Object_95"
            castShadow
            receiveShadow
            geometry={nodes.Object_95.geometry}
            material={materials.M_D1}
          />
          <mesh
            name="Object_96"
            castShadow
            receiveShadow
            geometry={nodes.Object_96.geometry}
            material={materials.M_D2}
          />
          <mesh
            name="Object_97"
            castShadow
            receiveShadow
            geometry={nodes.Object_97.geometry}
            material={materials.Plastic_D1}
          />
          <mesh
            name="Object_98"
            castShadow
            receiveShadow
            geometry={nodes.Object_98.geometry}
            material={materials.Plastic_L1}
          />
          <mesh
            name="Object_99"
            castShadow
            receiveShadow
            geometry={nodes.Object_99.geometry}
            material={materials.Plastic_Base}
          />
        </group>
        <group name="Cube203_24" scale={0.28321052}>
          <mesh
            name="Object_101"
            castShadow
            receiveShadow
            geometry={nodes.Object_101.geometry}
            material={materials.Red_L1}
          />
          <mesh
            name="Object_102"
            castShadow
            receiveShadow
            geometry={nodes.Object_102.geometry}
            material={materials.Red_Basic}
          />
          <mesh
            name="Object_103"
            castShadow
            receiveShadow
            geometry={nodes.Object_103.geometry}
            material={materials.Red_D1}
          />
          <mesh
            name="Object_104"
            castShadow
            receiveShadow
            geometry={nodes.Object_104.geometry}
            material={materials.Grey_L1}
          />
        </group>
        <group
          name="Cylinder155_26"
          rotation={[-0.0003654, -6e-7, -Math.PI / 2]}
          scale={[0.26988748, 0.26988751, 0.26988748]}>
          <mesh
            name="Object_108"
            castShadow
            receiveShadow
            geometry={nodes.Object_108.geometry}
            material={materials.M_L1}
          />
          <mesh
            name="Object_109"
            castShadow
            receiveShadow
            geometry={nodes.Object_109.geometry}
            material={materials.M_Basic}
          />
          <mesh
            name="Object_110"
            castShadow
            receiveShadow
            geometry={nodes.Object_110.geometry}
            material={materials.Plastic_L1}
          />
          <mesh
            name="Object_111"
            castShadow
            receiveShadow
            geometry={nodes.Object_111.geometry}
            material={materials.Plastic_Base}
          />
        </group>
        <group
          name="Cylinder156_27"
          rotation={[-0.00036525, -7.2e-7, -Math.PI / 2]}
          scale={[0.28321046, 0.28321052, 0.28321046]}>
          <mesh
            name="Object_113"
            castShadow
            receiveShadow
            geometry={nodes.Object_113.geometry}
            material={materials.M_L1}
          />
          <mesh
            name="Object_114"
            castShadow
            receiveShadow
            geometry={nodes.Object_114.geometry}
            material={materials.Metall_Basic}
          />
          <mesh
            name="Object_115"
            castShadow
            receiveShadow
            geometry={nodes.Object_115.geometry}
            material={materials.Metall_D1}
          />
        </group>
        <group
          name="Cylinder158_29"
          rotation={[-0.0003654, -6e-7, -Math.PI / 2]}
          scale={[0.26988748, 0.26988751, 0.26988748]}>
          <mesh
            name="Object_119"
            castShadow
            receiveShadow
            geometry={nodes.Object_119.geometry}
            material={materials.M_D1}
          />
          <mesh
            name="Object_120"
            castShadow
            receiveShadow
            geometry={nodes.Object_120.geometry}
            material={materials.M_D2}
          />
          <mesh
            name="Object_121"
            castShadow
            receiveShadow
            geometry={nodes.Object_121.geometry}
            material={materials.Plastic_D1}
          />
          <mesh
            name="Object_122"
            castShadow
            receiveShadow
            geometry={nodes.Object_122.geometry}
            material={materials.Plastic_Base}
          />
        </group>
        <group name="Cylinder164_31" rotation={[-0.77143577, 0, 0]} scale={0.28321052}>
          <mesh
            name="Object_126"
            castShadow
            receiveShadow
            geometry={nodes.Object_126.geometry}
            material={materials['Material.004']}
          />
          <mesh
            name="Object_127"
            castShadow
            receiveShadow
            geometry={nodes.Object_127.geometry}
            material={materials.Grey_D2}
          />
          <mesh
            name="Object_128"
            castShadow
            receiveShadow
            geometry={nodes.Object_128.geometry}
            material={materials.Plastic_D1}
          />
          <mesh
            name="Object_129"
            castShadow
            receiveShadow
            geometry={nodes.Object_129.geometry}
            material={materials.Rubber_Basic}
          />
          <mesh
            name="Object_130"
            castShadow
            receiveShadow
            geometry={nodes.Object_130.geometry}
            material={materials.Plastic_L1}
          />
          <mesh
            name="Object_131"
            castShadow
            receiveShadow
            geometry={nodes.Object_131.geometry}
            material={materials.Plastic_Base}
          />
          <mesh
            name="Object_132"
            castShadow
            receiveShadow
            geometry={nodes.Object_132.geometry}
            material={materials.Plastic_D2}
          />
          <mesh
            name="Object_133"
            castShadow
            receiveShadow
            geometry={nodes.Object_133.geometry}
            material={materials.Yellow_L1}
          />
        </group>
        <group
          name="Cylinder165_32"
          rotation={[-1.32946826, 0, 0]}
          scale={[0.28321052, 0.28321049, 0.28321049]}>
          <mesh
            name="Object_135"
            castShadow
            receiveShadow
            geometry={nodes.Object_135.geometry}
            material={materials['Material.011']}
          />
          <mesh
            name="Object_136"
            castShadow
            receiveShadow
            geometry={nodes.Object_136.geometry}
            material={materials['Material.012']}
          />
        </group>
        <group
          name="Cylinder176_35"
          rotation={[Math.PI / 2, -Math.PI / 2, 0]}
          scale={[0.28321052, 0.31251329, 0.28321052]}>
          <mesh
            name="Object_142"
            castShadow
            receiveShadow
            geometry={nodes.Object_142.geometry}
            material={materials.Metall_Basic}
          />
          <mesh
            name="Object_143"
            castShadow
            receiveShadow
            geometry={nodes.Object_143.geometry}
            material={materials.Metall_D1}
          />
          <mesh
            name="Object_144"
            castShadow
            receiveShadow
            geometry={nodes.Object_144.geometry}
            material={materials.Metall_D2}
          />
        </group>
        <group name="Cylinder177_36" rotation={[-2.58577315, -7.6e-7, -Math.PI]} scale={0.28321052}>
          <mesh
            name="Object_146"
            castShadow
            receiveShadow
            geometry={nodes.Object_146.geometry}
            material={materials.Metall_Basic}
          />
          <mesh
            name="Object_147"
            castShadow
            receiveShadow
            geometry={nodes.Object_147.geometry}
            material={materials.Metall_D1}
          />
          <mesh
            name="Object_148"
            castShadow
            receiveShadow
            geometry={nodes.Object_148.geometry}
            material={materials.Metall_D2}
          />
        </group>
        <group name="obt001_37" scale={0.28321052}>
          <mesh
            name="Object_150"
            castShadow
            receiveShadow
            geometry={nodes.Object_150.geometry}
            material={materials.CARBONE}
          />
          <mesh
            name="Object_151"
            castShadow
            receiveShadow
            geometry={nodes.Object_151.geometry}
            material={materials['Material.001']}
          />
        </group>
        <group
          name="pneu_ar-gauche_3002_41"
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.00036219, 0.00038301, 0.00038301]}>
          <mesh
            name="Object_155"
            castShadow
            receiveShadow
            geometry={nodes.Object_155.geometry}
            material={materials['Material.002']}
          />
          <mesh
            name="Object_156"
            castShadow
            receiveShadow
            geometry={nodes.Object_156.geometry}
            material={materials['Material.001']}
          />
        </group>
        <group
          name="SpineB005_44"
          position={[0.01732175, 0.44445336, -0.0030977]}
          scale={0.28321052}>
          <mesh
            name="Object_162"
            castShadow
            receiveShadow
            geometry={nodes.Object_162.geometry}
            material={materials.M_L1}
          />
          <mesh
            name="Object_163"
            castShadow
            receiveShadow
            geometry={nodes.Object_163.geometry}
            material={materials.CARBONE}
          />
          <mesh
            name="Object_164"
            castShadow
            receiveShadow
            geometry={nodes.Object_164.geometry}
            material={materials.M_D1}
          />
          <mesh
            name="Object_165"
            castShadow
            receiveShadow
            geometry={nodes.Object_165.geometry}
            material={materials.M_D2}
          />
          <mesh
            name="Object_166"
            castShadow
            receiveShadow
            geometry={nodes.Object_166.geometry}
            material={materials.Red_Basic}
          />
          <mesh
            name="Object_167"
            castShadow
            receiveShadow
            geometry={nodes.Object_167.geometry}
            material={materials['Material.010']}
          />
        </group>
        <mesh
          name="Object_12"
          castShadow
          receiveShadow
          geometry={nodes.Object_12.geometry}
          material={materials.Material}
          scale={0.28321052}
        />
        <mesh
          name="Object_14"
          castShadow
          receiveShadow
          geometry={nodes.Object_14.geometry}
          material={materials['Material.007']}
          position={[0, -0.00919022, -0.00170817]}
          scale={0.28321052}
        />
        <mesh
          name="Object_52"
          castShadow
          receiveShadow
          geometry={nodes.Object_52.geometry}
          material={materials['Material.006']}
          scale={0.28321052}
        />
        <mesh
          name="Object_54"
          castShadow
          receiveShadow
          geometry={nodes.Object_54.geometry}
          material={materials['Material.014']}
          rotation={[1.11716212, 0, 0]}
          scale={[0.28321052, 0.28321049, 0.28321049]}
        />
        <mesh
          name="Object_68"
          castShadow
          receiveShadow
          geometry={nodes.Object_68.geometry}
          material={materials.Metall_D2}
          rotation={[0.64417989, 0, 0]}
          scale={0.28321052}
        />
        <mesh
          name="Object_106"
          castShadow
          receiveShadow
          geometry={nodes.Object_106.geometry}
          material={materials['Material.016']}
          scale={0.28321052}
        />
        <mesh
          name="Object_117"
          castShadow
          receiveShadow
          geometry={nodes.Object_117.geometry}
          material={materials.Plastic_D1}
          rotation={[-0.0003654, -6e-7, -Math.PI / 2]}
          scale={[0.26988748, 0.26988751, 0.26988748]}
        />
        <mesh
          name="Object_124"
          castShadow
          receiveShadow
          geometry={nodes.Object_124.geometry}
          material={materials['Material.008']}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.28321052}
        />
        <mesh
          name="Object_138"
          castShadow
          receiveShadow
          geometry={nodes.Object_138.geometry}
          material={materials.material}
          rotation={[0.26569851, 1.04484763, -2.01500161]}
          scale={0.28321052}
        />
        <mesh
          name="Object_140"
          castShadow
          receiveShadow
          geometry={nodes.Object_140.geometry}
          material={materials.material}
          rotation={[-2.50136546, 1.20565918, 0.60969326]}
          scale={[0.28321052, 0.28321049, 0.28321052]}
        />
        <mesh
          name="Object_153"
          castShadow
          receiveShadow
          geometry={nodes.Object_153.geometry}
          material={materials.Rubber_Basic}
          scale={[0.26658496, 0.28321052, 0.28321052]}
        />
        <mesh
          name="Object_158"
          castShadow
          receiveShadow
          geometry={nodes.Object_158.geometry}
          material={materials['Rubber_Tire.002']}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.00036219, 0.00038301, 0.00038301]}
        />
        <mesh
          name="Object_160"
          castShadow
          receiveShadow
          geometry={nodes.Object_160.geometry}
          material={materials['Material.007']}
          rotation={[-Math.PI / 2, -2.4e-7, -Math.PI]}
          scale={0.28321052}
        />
        <mesh
          name="Object_169"
          castShadow
          receiveShadow
          geometry={nodes.Object_169.geometry}
          material={materials['Material.015']}
          rotation={[-0.11291789, 0, 0]}
          scale={[0.28321052, 0.28321049, 0.28321049]}
        />
      </group>
      {/* <mesh
        name="Object_171"
        castShadow
        receiveShadow
        geometry={nodes.Object_171.geometry}
        material={materials['Material.002']}
        position={[0.49030086, 1.37289751, 0.36969203]}
        rotation={[0.51153932, 0, -Math.PI / 2]}
        scale={[0.12605916, 0.12605914, 0.12605916]}
        visible={false}
      /> */}

     
      {/* <mesh
        name="Object_173"
        castShadow
        receiveShadow
        geometry={nodes.Object_173.geometry}
        material={materials['Material.002']}
        position={[-0.49337113, 0.86643839, 0.06426473]}
        rotation={[0.54558904, 6e-8, Math.PI / 2]}
        scale={[0.12605916, 0.12605914, 0.12605916]}
      /> */}
    </group>
  )
}

useGLTF.preload('/models/dji_drone.glb')